[package]
name = "rust-node"
version = "0.1.0"
authors = ["scottperkins"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
kafka = "0.8.0"
